language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: rQQ35xYGLanVItRf5G2LZJRjnrMGH5Gz1/md006MydIQoY/vDfjWsI+tDSEOh3yNvDe3EIk06zQwRRxYQXM/DkBwdZVSOG/MNJJ8wTRb+KC6eCgcGBYQunSAQpcVsO7APeqqL+Kc6kPo2nnUjXf3GTidVRfy+uxoxWqEOS6/E5/KOcq5ZWNrGdKtL97JrMwjnVGbpuaUJxIy4yZq9Elbv4QHyOOG8PprielsYBGylUrrSt9sqNkU6bxRfG/UQNc0lJHLqNuznEAQYu87E1ieKagctiFX1Za2gE2JrOdWIDE3PVqCDEZWltmlChEJbdMgis1sF8Y0XKHjKHbxX2Asx/QXQADaxo4pe/+zf2h8h/4xmR7F74ipXHP3C/CnAEBQJjG+knxgcg8BoCaNq+J4+zWSpcH8zOR2CaOKgQGgbFGDOVBBmcLs8ukOKxCWEE7fPT4G+r6IRSE/fX9yvC7ldqzS3d0Hf4I94AJ/+5bHgszHdMVLJtc3mnYUk262/3p5h3KL2WKITyGhwzGXUWIU0VtTwHUQel+zWBlFDN4pCzPnBjv87/kx4dUvZ6S5fLxiekVScjCgH0LIozRPGrgyJzscHTG7Q5egPgVFQxDW/HT+In16vgMWGrHuW6HImoNsVTdmvmSJwI02owQkTeMBfONEFz7SCZmnXG/9Rt0Py/Y=
  file:
    - 'svg-tag-names.js'
    - 'svg-tag-names.min.js'
  on:
    tags: true
